### ISSUE TITLE
Can't throw or drop items near the walls

### ISSUE THREAD

**Issue by JTDevil666** [Sourdough-Games/Pawn-Shop-Simulator#37]
When you are at a given distance from the wall (not close enough in my eyes), it isn't possible to throw or drop items on the floor.
In the picture below, I wanna keep all the leftover pictures together in the corner, but I can't drop any items near enough the wall.
(Green arrow: distance, red arrow: where I want the picture)
![2024-04-12_22-30-10](https://github.com/Sourdough-Games/Pawn-Shop-Simulator/assets/166335457/159e9b40-167b-4fcc-863d-7fd4dc50f862)

**Comment by GrumpyCrouton** [comment]
This is intentional due to https://github.com/Sourdough-Games/Pawn-Shop-Simulator/issues/28#issue-2238328587

Will be resolved when I add a system of precisely placing objects. I could possibly lower the distance you have to be from the wall but I made it what it is because of big objects like the washer

Thoughts? @JTDevil666

**Comment by JTDevil666** [comment]
I think as long as it will be fixed when you are implementing a system of precisely placing objects, it's okay - so this issue can eventually be closed :)

**Comment by GrumpyCrouton** [comment]
Well it would be "fixed" by not needing to throw the object when standing close to the wall. This issue itself would still exist.
I am going to play around with lowering the distance so it's less noticeable. I'll probably also add a little more force to the player throwing so you can throw it from a little bit further away
